//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail_achat
    {
        public int id_detail_achat { get; set; }
        public int id_achat { get; set; }
        public int id_produit { get; set; }
        public decimal ppv { get; set; }
        public decimal pph { get; set; }
        public int stock_initial { get; set; }
        public int stock_actuel { get; set; }
        public System.DateTime peremption { get; set; }
    
        public virtual achat achat { get; set; }
        public virtual produit produit { get; set; }
    }
}
