//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeStock
{
    using System;
    
    public partial class sp_serch_fourn_Result
    {
        public int id_fournisseur { get; set; }
        public string nom_fournisseur { get; set; }
        public string telephone { get; set; }
    }
}
