//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class vente_detail
    {
        public int id_detail { get; set; }
        public int id_vente { get; set; }
        public int id_produit { get; set; }
        public string nom_produit { get; set; }
        public int quantity { get; set; }
        public string prix { get; set; }
        public string remise { get; set; }
        public string total { get; set; }
    
        public virtual produit produit { get; set; }
        public virtual vente vente { get; set; }
    }
}
